apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexearn-platform
  namespace: nexearn
  labels:
    app: nexearn-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexearn-platform
  template:
    metadata:
      labels:
        app: nexearn-platform
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres..."
              until pg_isready -h nexearn-postgres -U nexearn -d nexearn; do
                sleep 2
              done
              echo "Postgres is ready."
      containers:
        - name: nexearn-platform
          image: nexearn-app:e2e
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: NEXEARN_APP_ENV
              value: "production"
            - name: NEXEARN_DEBUG
              value: "0"
            - name: NEXEARN_LOG_LEVEL
              value: "info"
            - name: NEXEARN_ALLOWED_HOSTS
              value: ""
          envFrom:
            - secretRef:
                name: nexearn-secrets
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 1000m
              memory: 768Mi
