apiVersion: v1
kind: Secret
metadata:
  name: nexearn-secrets
  namespace: nexearn
type: Opaque
stringData:
  NEXEARN_JWT_SECRET: "FsATDLni0lKlLILcNs__te8CnTufkNTibs6n8FSlgOVbSRNkf8pCbNp-j6259tUK"
  NEXEARN_DATABASE_URL: "postgresql+asyncpg://nexearn:nexearn@nexearn-postgres:5432/nexearn"
  NEXEARN_REDIS_URL: "redis://nexearn-redis:6379/0"
  POSTGRES_USER: "nexearn"
  POSTGRES_PASSWORD: "nexearn"
  POSTGRES_DB: "nexearn"
