apiVersion: v1
kind: Service
metadata:
  name: nexearn-platform
  namespace: nexearn
  labels:
    app: nexearn-platform
spec:
  type: ClusterIP
  selector:
    app: nexearn-platform
  ports:
    - name: http
      port: 80
      targetPort: http
